# Services definition for a Kontalk server
# DO NOT RUN docker-compose on this file directly
# Use ./launcher start

version: '3'

services:
  db:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: on-failure
    environment:
      MYSQL_DATABASE: kontalk
      MYSQL_USER: kontalk

  xmpp:
    depends_on:
      - db
    image: kontalk/xmppserver
    ports:
      - "${XMPP_LISTEN_PORT}:5222"
      - "${XMPPS_LISTEN_PORT}:5223"
      - "${XMPPS2S_LISTEN_PORT}:5269"
    volumes:
      - xmpp_data:/home/kontalk/data
      - ./data:/tmp/data
      - ./data/tigase.conf:/home/kontalk/kontalk/tigase-kontalk/etc/tigase.conf
      - ./data/trusted.pem:/home/kontalk/kontalk/tigase-kontalk/trusted.pem
    restart: on-failure
    environment:
      MYSQL_DATABASE: kontalk
      MYSQL_USER: kontalk

  httpupload:
    image: kontalk/httpupload
    ports:
      - "${HTTPUPLOAD_LISTEN_PORT}:8828"
    volumes:
      - httpupload_data:/home/kontalk/disk
      - ./data/config.yml.in:/tmp/config.yml.in
    restart: on-failure

volumes:
  db_data:
  xmpp_data:
  httpupload_data:
